/**
 * Application error codes for structured error handling.
 * Used in API responses and inter-service communication.
 */
export const ERROR_CODES = {
  // Authentication (1xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_TOKEN_INVALID: 'AUTH_1003',
  AUTH_2FA_REQUIRED: 'AUTH_1004',
  AUTH_2FA_INVALID: 'AUTH_1005',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_1006',
  AUTH_ACCOUNT_DELETED: 'AUTH_1007',

  // Authorization (2xxx)
  AUTHZ_FORBIDDEN: 'AUTHZ_2001',
  AUTHZ_NOT_WORKSPACE_MEMBER: 'AUTHZ_2002',
  AUTHZ_INSUFFICIENT_ROLE: 'AUTHZ_2003',

  // Resource (3xxx)
  RESOURCE_NOT_FOUND: 'RES_3001',
  RESOURCE_ALREADY_EXISTS: 'RES_3002',
  RESOURCE_CONFLICT: 'RES_3003',

  // Validation (4xxx)
  VALIDATION_FAILED: 'VAL_4001',
  VALIDATION_FILE_TOO_LARGE: 'VAL_4002',
  VALIDATION_INVALID_MIME_TYPE: 'VAL_4003',
  VALIDATION_INVALID_DATE_RANGE: 'VAL_4004',

  // Rate Limiting (5xxx)
  RATE_LIMIT_EXCEEDED: 'RATE_5001',
  RATE_LIMIT_API_KEY: 'RATE_5002',

  // Agent (6xxx)
  AGENT_SPAWN_FAILED: 'AGENT_6001',
  AGENT_TASK_FAILED: 'AGENT_6002',
  AGENT_TIMEOUT: 'AGENT_6003',
  AGENT_CONTEXT_LOST: 'AGENT_6004',

  // Integration (7xxx)
  INTEGRATION_NOT_CONNECTED: 'INT_7001',
  INTEGRATION_TOKEN_EXPIRED: 'INT_7002',
  INTEGRATION_API_ERROR: 'INT_7003',

  // Cost (8xxx)
  COST_LIMIT_EXCEEDED: 'COST_8001',
  COST_NO_API_KEY: 'COST_8002',
  COST_PROVIDER_ERROR: 'COST_8003',

  // File Storage (9xxx)
  FILE_UPLOAD_FAILED: 'FILE_9001',
  FILE_NOT_FOUND: 'FILE_9002',
  FILE_STORAGE_FULL: 'FILE_9003',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
